blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/hegelband/dizy/discussions
    about: This issue tracker is not for support questions. Please refer to our Discussions.
  - name: 💬 Chat
    url: https://t.me/DizyChat
    about: Want to discuss Dizy with others? Check out our chat.
