# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: macos-latest
    steps:
      # Your original steps
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: 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
      - uses: actions/setup-node@v4
        with:
          node-version: 18.12.0
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test:cover
      - name: Coverage
        run: npm run cover:report


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
